[2025-06-04T10:57:39.454+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-04T10:57:39.465+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: curry_medallion_etl.submit_bronze_etl_job manual__2025-06-04T10:57:38.377169+00:00 [queued]>
[2025-06-04T10:57:39.469+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: curry_medallion_etl.submit_bronze_etl_job manual__2025-06-04T10:57:38.377169+00:00 [queued]>
[2025-06-04T10:57:39.469+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-06-04T10:57:39.476+0000] {taskinstance.py:2889} INFO - Executing <Task(SparkSubmitOperator): submit_bronze_etl_job> on 2025-06-04 10:57:38.377169+00:00
[2025-06-04T10:57:39.479+0000] {standard_task_runner.py:72} INFO - Started process 239 to run task
[2025-06-04T10:57:39.481+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'curry_medallion_etl', 'submit_bronze_etl_job', 'manual__2025-06-04T10:57:38.377169+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/medallion_sales_etl_dag.py', '--cfg-path', '/tmp/tmp3t8ui_o1']
[2025-06-04T10:57:39.483+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask submit_bronze_etl_job
[2025-06-04T10:57:39.517+0000] {task_command.py:467} INFO - Running <TaskInstance: curry_medallion_etl.submit_bronze_etl_job manual__2025-06-04T10:57:38.377169+00:00 [running]> on host 274c77453f4c
[2025-06-04T10:57:39.567+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='qdinh18' AIRFLOW_CTX_DAG_ID='curry_medallion_etl' AIRFLOW_CTX_TASK_ID='submit_bronze_etl_job' AIRFLOW_CTX_EXECUTION_DATE='2025-06-04T10:57:38.377169+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-04T10:57:38.377169+00:00'
[2025-06-04T10:57:39.567+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-06-04T10:57:39.587+0000] {base.py:84} INFO - Retrieving connection 'spark_default'
[2025-06-04T10:57:39.588+0000] {spark_submit.py:474} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --conf spark.executor.memory=2g --conf spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension --conf spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog --conf spark.hadoop.fs.s3a.endpoint=http://minio:9000 --conf spark.hadoop.fs.s3a.access.key=minioadmin --conf spark.hadoop.fs.s3a.secret.key=****** --conf spark.hadoop.fs.s3a.path.style.access=true --conf spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem --packages org.apache.hadoop:hadoop-aws:3.3.4,com.amazonaws:aws-java-sdk-bundle:1.12.262,io.delta:delta-spark_2.12:3.1.0 --name bronze_sc_stats_etl --verbose --queue root.default --deploy-mode client /opt/***/dags/bronze_ingestion_sc_stats_etl.py --output_path s3a://mybucket/bronze/curry_raw_data/
[2025-06-04T10:57:40.616+0000] {spark_submit.py:644} INFO - Using properties file: null
[2025-06-04T10:57:40.674+0000] {spark_submit.py:644} INFO - Parsed arguments:
[2025-06-04T10:57:40.674+0000] {spark_submit.py:644} INFO - master                  spark://spark-master:7077
[2025-06-04T10:57:40.674+0000] {spark_submit.py:644} INFO - remote                  null
[2025-06-04T10:57:40.675+0000] {spark_submit.py:644} INFO - deployMode              client
[2025-06-04T10:57:40.675+0000] {spark_submit.py:644} INFO - executorMemory          2g
[2025-06-04T10:57:40.675+0000] {spark_submit.py:644} INFO - executorCores           null
[2025-06-04T10:57:40.675+0000] {spark_submit.py:644} INFO - totalExecutorCores      null
[2025-06-04T10:57:40.675+0000] {spark_submit.py:644} INFO - propertiesFile          null
[2025-06-04T10:57:40.675+0000] {spark_submit.py:644} INFO - driverMemory            null
[2025-06-04T10:57:40.675+0000] {spark_submit.py:644} INFO - driverCores             null
[2025-06-04T10:57:40.675+0000] {spark_submit.py:644} INFO - driverExtraClassPath    null
[2025-06-04T10:57:40.676+0000] {spark_submit.py:644} INFO - driverExtraLibraryPath  null
[2025-06-04T10:57:40.676+0000] {spark_submit.py:644} INFO - driverExtraJavaOptions  null
[2025-06-04T10:57:40.676+0000] {spark_submit.py:644} INFO - supervise               false
[2025-06-04T10:57:40.676+0000] {spark_submit.py:644} INFO - queue                   root.default
[2025-06-04T10:57:40.676+0000] {spark_submit.py:644} INFO - numExecutors            null
[2025-06-04T10:57:40.676+0000] {spark_submit.py:644} INFO - files                   null
[2025-06-04T10:57:40.676+0000] {spark_submit.py:644} INFO - pyFiles                 null
[2025-06-04T10:57:40.676+0000] {spark_submit.py:644} INFO - archives                null
[2025-06-04T10:57:40.676+0000] {spark_submit.py:644} INFO - mainClass               null
[2025-06-04T10:57:40.677+0000] {spark_submit.py:644} INFO - primaryResource         file:/opt/***/dags/bronze_ingestion_sc_stats_etl.py
[2025-06-04T10:57:40.677+0000] {spark_submit.py:644} INFO - name                    bronze_sc_stats_etl
[2025-06-04T10:57:40.677+0000] {spark_submit.py:644} INFO - childArgs               [--output_path s3a://mybucket/bronze/curry_raw_data/]
[2025-06-04T10:57:40.677+0000] {spark_submit.py:644} INFO - jars                    null
[2025-06-04T10:57:40.677+0000] {spark_submit.py:644} INFO - packages                org.apache.hadoop:hadoop-aws:3.3.4,com.amazonaws:aws-java-sdk-bundle:1.12.262,io.delta:delta-spark_2.12:3.1.0
[2025-06-04T10:57:40.677+0000] {spark_submit.py:644} INFO - packagesExclusions      null
[2025-06-04T10:57:40.677+0000] {spark_submit.py:644} INFO - repositories            null
[2025-06-04T10:57:40.677+0000] {spark_submit.py:644} INFO - verbose                 true
[2025-06-04T10:57:40.677+0000] {spark_submit.py:644} INFO - 
[2025-06-04T10:57:40.678+0000] {spark_submit.py:644} INFO - Spark properties used, including those specified through
[2025-06-04T10:57:40.678+0000] {spark_submit.py:644} INFO - --conf and those from the properties file null:
[2025-06-04T10:57:40.678+0000] {spark_submit.py:644} INFO - (spark.executor.memory,2g)
[2025-06-04T10:57:40.678+0000] {spark_submit.py:644} INFO - (spark.hadoop.fs.s3a.access.key,*********(redacted))
[2025-06-04T10:57:40.678+0000] {spark_submit.py:644} INFO - (spark.hadoop.fs.s3a.endpoint,http://minio:9000)
[2025-06-04T10:57:40.678+0000] {spark_submit.py:644} INFO - (spark.hadoop.fs.s3a.impl,org.apache.hadoop.fs.s3a.S3AFileSystem)
[2025-06-04T10:57:40.678+0000] {spark_submit.py:644} INFO - (spark.hadoop.fs.s3a.path.style.access,true)
[2025-06-04T10:57:40.678+0000] {spark_submit.py:644} INFO - (spark.hadoop.fs.s3a.secret.key,*********(redacted))
[2025-06-04T10:57:40.678+0000] {spark_submit.py:644} INFO - (spark.sql.catalog.spark_catalog,org.apache.spark.sql.delta.catalog.DeltaCatalog)
[2025-06-04T10:57:40.678+0000] {spark_submit.py:644} INFO - (spark.sql.extensions,io.delta.sql.DeltaSparkSessionExtension)
[2025-06-04T10:57:40.678+0000] {spark_submit.py:644} INFO - 
[2025-06-04T10:57:40.679+0000] {spark_submit.py:644} INFO - 
[2025-06-04T10:57:40.758+0000] {spark_submit.py:644} INFO - :: loading settings :: url = jar:file:/home/***/.local/lib/python3.11/site-packages/pyspark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2025-06-04T10:57:40.804+0000] {spark_submit.py:644} INFO - Ivy Default Cache set to: /home/***/.ivy2/cache
[2025-06-04T10:57:40.805+0000] {spark_submit.py:644} INFO - The jars for the packages stored in: /home/***/.ivy2/jars
[2025-06-04T10:57:40.807+0000] {spark_submit.py:644} INFO - org.apache.hadoop#hadoop-aws added as a dependency
[2025-06-04T10:57:40.808+0000] {spark_submit.py:644} INFO - com.amazonaws#aws-java-sdk-bundle added as a dependency
[2025-06-04T10:57:40.808+0000] {spark_submit.py:644} INFO - io.delta#delta-spark_2.12 added as a dependency
[2025-06-04T10:57:40.808+0000] {spark_submit.py:644} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-89d9d596-a597-4514-ab16-70e0c3f45aa0;1.0
[2025-06-04T10:57:40.808+0000] {spark_submit.py:644} INFO - confs: [default]
[2025-06-04T10:57:45.212+0000] {spark_submit.py:644} INFO - found org.apache.hadoop#hadoop-aws;3.3.4 in central
[2025-06-04T10:57:46.828+0000] {spark_submit.py:644} INFO - found com.amazonaws#aws-java-sdk-bundle;1.12.262 in central
[2025-06-04T10:57:49.815+0000] {spark_submit.py:644} INFO - found org.wildfly.openssl#wildfly-openssl;1.0.7.Final in central
[2025-06-04T10:57:50.191+0000] {spark_submit.py:644} INFO - found io.delta#delta-spark_2.12;3.1.0 in central
[2025-06-04T10:57:50.558+0000] {spark_submit.py:644} INFO - found io.delta#delta-storage;3.1.0 in central
[2025-06-04T10:57:52.785+0000] {spark_submit.py:644} INFO - found org.antlr#antlr4-runtime;4.9.3 in central
[2025-06-04T10:57:52.973+0000] {spark_submit.py:644} INFO - downloading https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.4/hadoop-aws-3.3.4.jar ...
[2025-06-04T10:57:53.676+0000] {spark_submit.py:644} INFO - [SUCCESSFUL ] org.apache.hadoop#hadoop-aws;3.3.4!hadoop-aws.jar (880ms)
[2025-06-04T10:57:53.853+0000] {spark_submit.py:644} INFO - downloading https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.262/aws-java-sdk-bundle-1.12.262.jar ...
[2025-06-04T10:58:06.485+0000] {spark_submit.py:644} INFO - [SUCCESSFUL ] com.amazonaws#aws-java-sdk-bundle;1.12.262!aws-java-sdk-bundle.jar (12807ms)
[2025-06-04T10:58:06.662+0000] {spark_submit.py:644} INFO - downloading https://repo1.maven.org/maven2/io/delta/delta-spark_2.12/3.1.0/delta-spark_2.12-3.1.0.jar ...
[2025-06-04T10:58:07.062+0000] {spark_submit.py:644} INFO - [SUCCESSFUL ] io.delta#delta-spark_2.12;3.1.0!delta-spark_2.12.jar (576ms)
[2025-06-04T10:58:07.241+0000] {spark_submit.py:644} INFO - downloading https://repo1.maven.org/maven2/org/wildfly/openssl/wildfly-openssl/1.0.7.Final/wildfly-openssl-1.0.7.Final.jar ...
[2025-06-04T10:58:07.437+0000] {spark_submit.py:644} INFO - [SUCCESSFUL ] org.wildfly.openssl#wildfly-openssl;1.0.7.Final!wildfly-openssl.jar (375ms)
[2025-06-04T10:58:07.617+0000] {spark_submit.py:644} INFO - downloading https://repo1.maven.org/maven2/io/delta/delta-storage/3.1.0/delta-storage-3.1.0.jar ...
[2025-06-04T10:58:07.800+0000] {spark_submit.py:644} INFO - [SUCCESSFUL ] io.delta#delta-storage;3.1.0!delta-storage.jar (361ms)
[2025-06-04T10:58:07.979+0000] {spark_submit.py:644} INFO - downloading https://repo1.maven.org/maven2/org/antlr/antlr4-runtime/4.9.3/antlr4-runtime-4.9.3.jar ...
[2025-06-04T10:58:08.161+0000] {spark_submit.py:644} INFO - [SUCCESSFUL ] org.antlr#antlr4-runtime;4.9.3!antlr4-runtime.jar (359ms)
[2025-06-04T10:58:08.162+0000] {spark_submit.py:644} INFO - :: resolution report :: resolve 11987ms :: artifacts dl 15366ms
[2025-06-04T10:58:08.163+0000] {spark_submit.py:644} INFO - :: modules in use:
[2025-06-04T10:58:08.165+0000] {spark_submit.py:644} INFO - com.amazonaws#aws-java-sdk-bundle;1.12.262 from central in [default]
[2025-06-04T10:58:08.166+0000] {spark_submit.py:644} INFO - io.delta#delta-spark_2.12;3.1.0 from central in [default]
[2025-06-04T10:58:08.166+0000] {spark_submit.py:644} INFO - io.delta#delta-storage;3.1.0 from central in [default]
[2025-06-04T10:58:08.167+0000] {spark_submit.py:644} INFO - org.antlr#antlr4-runtime;4.9.3 from central in [default]
[2025-06-04T10:58:08.167+0000] {spark_submit.py:644} INFO - org.apache.hadoop#hadoop-aws;3.3.4 from central in [default]
[2025-06-04T10:58:08.167+0000] {spark_submit.py:644} INFO - org.wildfly.openssl#wildfly-openssl;1.0.7.Final from central in [default]
[2025-06-04T10:58:08.167+0000] {spark_submit.py:644} INFO - ---------------------------------------------------------------------
[2025-06-04T10:58:08.167+0000] {spark_submit.py:644} INFO - |                  |            modules            ||   artifacts   |
[2025-06-04T10:58:08.167+0000] {spark_submit.py:644} INFO - |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2025-06-04T10:58:08.168+0000] {spark_submit.py:644} INFO - ---------------------------------------------------------------------
[2025-06-04T10:58:08.168+0000] {spark_submit.py:644} INFO - |      default     |   6   |   6   |   6   |   0   ||   6   |   6   |
[2025-06-04T10:58:08.168+0000] {spark_submit.py:644} INFO - ---------------------------------------------------------------------
[2025-06-04T10:58:08.168+0000] {spark_submit.py:644} INFO - :: retrieving :: org.apache.spark#spark-submit-parent-89d9d596-a597-4514-ab16-70e0c3f45aa0
[2025-06-04T10:58:08.168+0000] {spark_submit.py:644} INFO - confs: [default]
[2025-06-04T10:58:08.567+0000] {spark_submit.py:644} INFO - 6 artifacts copied, 0 already retrieved (281149kB/403ms)
[2025-06-04T10:58:08.696+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:08 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-06-04T10:58:08.804+0000] {spark_submit.py:644} INFO - Main class:
[2025-06-04T10:58:08.805+0000] {spark_submit.py:644} INFO - org.apache.spark.deploy.PythonRunner
[2025-06-04T10:58:08.805+0000] {spark_submit.py:644} INFO - Arguments:
[2025-06-04T10:58:08.805+0000] {spark_submit.py:644} INFO - file:/opt/***/dags/bronze_ingestion_sc_stats_etl.py
[2025-06-04T10:58:08.806+0000] {spark_submit.py:644} INFO - file:///home/***/.ivy2/jars/org.apache.hadoop_hadoop-aws-3.3.4.jar,file:///home/***/.ivy2/jars/com.amazonaws_aws-java-sdk-bundle-1.12.262.jar,file:///home/***/.ivy2/jars/io.delta_delta-spark_2.12-3.1.0.jar,file:///home/***/.ivy2/jars/org.wildfly.openssl_wildfly-openssl-1.0.7.Final.jar,file:///home/***/.ivy2/jars/io.delta_delta-storage-3.1.0.jar,file:///home/***/.ivy2/jars/org.antlr_antlr4-runtime-4.9.3.jar
[2025-06-04T10:58:08.806+0000] {spark_submit.py:644} INFO - --output_path
[2025-06-04T10:58:08.806+0000] {spark_submit.py:644} INFO - s3a://mybucket/bronze/curry_raw_data/
[2025-06-04T10:58:08.807+0000] {spark_submit.py:644} INFO - Spark config:
[2025-06-04T10:58:08.807+0000] {spark_submit.py:644} INFO - (spark.app.name,bronze_sc_stats_etl)
[2025-06-04T10:58:08.807+0000] {spark_submit.py:644} INFO - (spark.app.submitTime,1749034688796)
[2025-06-04T10:58:08.807+0000] {spark_submit.py:644} INFO - (spark.executor.memory,2g)
[2025-06-04T10:58:08.807+0000] {spark_submit.py:644} INFO - (spark.files,file:///home/***/.ivy2/jars/org.apache.hadoop_hadoop-aws-3.3.4.jar,file:///home/***/.ivy2/jars/com.amazonaws_aws-java-sdk-bundle-1.12.262.jar,file:///home/***/.ivy2/jars/io.delta_delta-spark_2.12-3.1.0.jar,file:///home/***/.ivy2/jars/org.wildfly.openssl_wildfly-openssl-1.0.7.Final.jar,file:///home/***/.ivy2/jars/io.delta_delta-storage-3.1.0.jar,file:///home/***/.ivy2/jars/org.antlr_antlr4-runtime-4.9.3.jar)
[2025-06-04T10:58:08.807+0000] {spark_submit.py:644} INFO - (spark.hadoop.fs.s3a.access.key,*********(redacted))
[2025-06-04T10:58:08.807+0000] {spark_submit.py:644} INFO - (spark.hadoop.fs.s3a.endpoint,http://minio:9000)
[2025-06-04T10:58:08.807+0000] {spark_submit.py:644} INFO - (spark.hadoop.fs.s3a.impl,org.apache.hadoop.fs.s3a.S3AFileSystem)
[2025-06-04T10:58:08.808+0000] {spark_submit.py:644} INFO - (spark.hadoop.fs.s3a.path.style.access,true)
[2025-06-04T10:58:08.808+0000] {spark_submit.py:644} INFO - (spark.hadoop.fs.s3a.secret.key,*********(redacted))
[2025-06-04T10:58:08.808+0000] {spark_submit.py:644} INFO - (spark.jars,file:///home/***/.ivy2/jars/org.apache.hadoop_hadoop-aws-3.3.4.jar,file:///home/***/.ivy2/jars/com.amazonaws_aws-java-sdk-bundle-1.12.262.jar,file:///home/***/.ivy2/jars/io.delta_delta-spark_2.12-3.1.0.jar,file:///home/***/.ivy2/jars/org.wildfly.openssl_wildfly-openssl-1.0.7.Final.jar,file:///home/***/.ivy2/jars/io.delta_delta-storage-3.1.0.jar,file:///home/***/.ivy2/jars/org.antlr_antlr4-runtime-4.9.3.jar)
[2025-06-04T10:58:08.808+0000] {spark_submit.py:644} INFO - (spark.master,spark://spark-master:7077)
[2025-06-04T10:58:08.808+0000] {spark_submit.py:644} INFO - (spark.repl.local.jars,file:///home/***/.ivy2/jars/org.apache.hadoop_hadoop-aws-3.3.4.jar,file:///home/***/.ivy2/jars/com.amazonaws_aws-java-sdk-bundle-1.12.262.jar,file:///home/***/.ivy2/jars/io.delta_delta-spark_2.12-3.1.0.jar,file:///home/***/.ivy2/jars/org.wildfly.openssl_wildfly-openssl-1.0.7.Final.jar,file:///home/***/.ivy2/jars/io.delta_delta-storage-3.1.0.jar,file:///home/***/.ivy2/jars/org.antlr_antlr4-runtime-4.9.3.jar)
[2025-06-04T10:58:08.808+0000] {spark_submit.py:644} INFO - (spark.sql.catalog.spark_catalog,org.apache.spark.sql.delta.catalog.DeltaCatalog)
[2025-06-04T10:58:08.808+0000] {spark_submit.py:644} INFO - (spark.sql.extensions,io.delta.sql.DeltaSparkSessionExtension)
[2025-06-04T10:58:08.808+0000] {spark_submit.py:644} INFO - (spark.submit.deployMode,client)
[2025-06-04T10:58:08.809+0000] {spark_submit.py:644} INFO - (spark.submit.pyFiles,/home/***/.ivy2/jars/org.apache.hadoop_hadoop-aws-3.3.4.jar,/home/***/.ivy2/jars/com.amazonaws_aws-java-sdk-bundle-1.12.262.jar,/home/***/.ivy2/jars/io.delta_delta-spark_2.12-3.1.0.jar,/home/***/.ivy2/jars/org.wildfly.openssl_wildfly-openssl-1.0.7.Final.jar,/home/***/.ivy2/jars/io.delta_delta-storage-3.1.0.jar,/home/***/.ivy2/jars/org.antlr_antlr4-runtime-4.9.3.jar)
[2025-06-04T10:58:08.809+0000] {spark_submit.py:644} INFO - Classpath elements:
[2025-06-04T10:58:08.809+0000] {spark_submit.py:644} INFO - file:///home/***/.ivy2/jars/org.apache.hadoop_hadoop-aws-3.3.4.jar
[2025-06-04T10:58:08.809+0000] {spark_submit.py:644} INFO - file:///home/***/.ivy2/jars/com.amazonaws_aws-java-sdk-bundle-1.12.262.jar
[2025-06-04T10:58:08.809+0000] {spark_submit.py:644} INFO - file:///home/***/.ivy2/jars/io.delta_delta-spark_2.12-3.1.0.jar
[2025-06-04T10:58:08.809+0000] {spark_submit.py:644} INFO - file:///home/***/.ivy2/jars/org.wildfly.openssl_wildfly-openssl-1.0.7.Final.jar
[2025-06-04T10:58:08.809+0000] {spark_submit.py:644} INFO - file:///home/***/.ivy2/jars/io.delta_delta-storage-3.1.0.jar
[2025-06-04T10:58:08.809+0000] {spark_submit.py:644} INFO - file:///home/***/.ivy2/jars/org.antlr_antlr4-runtime-4.9.3.jar
[2025-06-04T10:58:08.810+0000] {spark_submit.py:644} INFO - 
[2025-06-04T10:58:08.810+0000] {spark_submit.py:644} INFO - 
[2025-06-04T10:58:09.592+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:09 INFO SparkContext: Running Spark version 3.5.2
[2025-06-04T10:58:09.593+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:09 INFO SparkContext: OS info Linux, 6.10.14-linuxkit, aarch64
[2025-06-04T10:58:09.593+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:09 INFO SparkContext: Java version 17.0.15
[2025-06-04T10:58:09.605+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:09 INFO ResourceUtils: ==============================================================
[2025-06-04T10:58:09.605+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:09 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-06-04T10:58:09.606+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:09 INFO ResourceUtils: ==============================================================
[2025-06-04T10:58:09.606+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:09 INFO SparkContext: Submitted application: BronzeIngestionStephenCurryStats
[2025-06-04T10:58:09.620+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:09 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(memory -> name: memory, amount: 2048, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-06-04T10:58:09.625+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:09 INFO ResourceProfile: Limiting resource is cpu
[2025-06-04T10:58:09.625+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:09 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-06-04T10:58:09.664+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:09 INFO SecurityManager: Changing view acls to: ***
[2025-06-04T10:58:09.665+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:09 INFO SecurityManager: Changing modify acls to: ***
[2025-06-04T10:58:09.665+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:09 INFO SecurityManager: Changing view acls groups to:
[2025-06-04T10:58:09.665+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:09 INFO SecurityManager: Changing modify acls groups to:
[2025-06-04T10:58:09.665+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:09 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: ***; groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY
[2025-06-04T10:58:09.807+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:09 INFO Utils: Successfully started service 'sparkDriver' on port 33287.
[2025-06-04T10:58:09.826+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:09 INFO SparkEnv: Registering MapOutputTracker
[2025-06-04T10:58:09.848+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:09 INFO SparkEnv: Registering BlockManagerMaster
[2025-06-04T10:58:09.858+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:09 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-06-04T10:58:09.858+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:09 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-06-04T10:58:09.860+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:09 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-06-04T10:58:09.875+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:09 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-13b17eb9-8c6d-41c1-b78e-78397120ffc4
[2025-06-04T10:58:09.883+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:09 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-06-04T10:58:09.892+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:09 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-06-04T10:58:09.971+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:09 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-06-04T10:58:10.010+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:10 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-06-04T10:58:10.035+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:10 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/org.apache.hadoop_hadoop-aws-3.3.4.jar at spark://274c77453f4c:33287/jars/org.apache.hadoop_hadoop-aws-3.3.4.jar with timestamp 1749034689585
[2025-06-04T10:58:10.035+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:10 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/com.amazonaws_aws-java-sdk-bundle-1.12.262.jar at spark://274c77453f4c:33287/jars/com.amazonaws_aws-java-sdk-bundle-1.12.262.jar with timestamp 1749034689585
[2025-06-04T10:58:10.035+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:10 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/io.delta_delta-spark_2.12-3.1.0.jar at spark://274c77453f4c:33287/jars/io.delta_delta-spark_2.12-3.1.0.jar with timestamp 1749034689585
[2025-06-04T10:58:10.035+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:10 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/org.wildfly.openssl_wildfly-openssl-1.0.7.Final.jar at spark://274c77453f4c:33287/jars/org.wildfly.openssl_wildfly-openssl-1.0.7.Final.jar with timestamp 1749034689585
[2025-06-04T10:58:10.036+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:10 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/io.delta_delta-storage-3.1.0.jar at spark://274c77453f4c:33287/jars/io.delta_delta-storage-3.1.0.jar with timestamp 1749034689585
[2025-06-04T10:58:10.036+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:10 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/org.antlr_antlr4-runtime-4.9.3.jar at spark://274c77453f4c:33287/jars/org.antlr_antlr4-runtime-4.9.3.jar with timestamp 1749034689585
[2025-06-04T10:58:10.037+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:10 INFO SparkContext: Added file file:///home/***/.ivy2/jars/org.apache.hadoop_hadoop-aws-3.3.4.jar at spark://274c77453f4c:33287/files/org.apache.hadoop_hadoop-aws-3.3.4.jar with timestamp 1749034689585
[2025-06-04T10:58:10.037+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:10 INFO Utils: Copying /home/***/.ivy2/jars/org.apache.hadoop_hadoop-aws-3.3.4.jar to /tmp/spark-bb0a74ef-ee4c-4e95-9400-d611794b9721/userFiles-ef176ae0-9763-4e99-8a21-e727e8640e7a/org.apache.hadoop_hadoop-aws-3.3.4.jar
[2025-06-04T10:58:10.049+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:10 INFO SparkContext: Added file file:///home/***/.ivy2/jars/com.amazonaws_aws-java-sdk-bundle-1.12.262.jar at spark://274c77453f4c:33287/files/com.amazonaws_aws-java-sdk-bundle-1.12.262.jar with timestamp 1749034689585
[2025-06-04T10:58:10.049+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:10 INFO Utils: Copying /home/***/.ivy2/jars/com.amazonaws_aws-java-sdk-bundle-1.12.262.jar to /tmp/spark-bb0a74ef-ee4c-4e95-9400-d611794b9721/userFiles-ef176ae0-9763-4e99-8a21-e727e8640e7a/com.amazonaws_aws-java-sdk-bundle-1.12.262.jar
[2025-06-04T10:58:10.207+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:10 INFO SparkContext: Added file file:///home/***/.ivy2/jars/io.delta_delta-spark_2.12-3.1.0.jar at spark://274c77453f4c:33287/files/io.delta_delta-spark_2.12-3.1.0.jar with timestamp 1749034689585
[2025-06-04T10:58:10.207+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:10 INFO Utils: Copying /home/***/.ivy2/jars/io.delta_delta-spark_2.12-3.1.0.jar to /tmp/spark-bb0a74ef-ee4c-4e95-9400-d611794b9721/userFiles-ef176ae0-9763-4e99-8a21-e727e8640e7a/io.delta_delta-spark_2.12-3.1.0.jar
[2025-06-04T10:58:10.213+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:10 INFO SparkContext: Added file file:///home/***/.ivy2/jars/org.wildfly.openssl_wildfly-openssl-1.0.7.Final.jar at spark://274c77453f4c:33287/files/org.wildfly.openssl_wildfly-openssl-1.0.7.Final.jar with timestamp 1749034689585
[2025-06-04T10:58:10.213+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:10 INFO Utils: Copying /home/***/.ivy2/jars/org.wildfly.openssl_wildfly-openssl-1.0.7.Final.jar to /tmp/spark-bb0a74ef-ee4c-4e95-9400-d611794b9721/userFiles-ef176ae0-9763-4e99-8a21-e727e8640e7a/org.wildfly.openssl_wildfly-openssl-1.0.7.Final.jar
[2025-06-04T10:58:10.215+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:10 INFO SparkContext: Added file file:///home/***/.ivy2/jars/io.delta_delta-storage-3.1.0.jar at spark://274c77453f4c:33287/files/io.delta_delta-storage-3.1.0.jar with timestamp 1749034689585
[2025-06-04T10:58:10.215+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:10 INFO Utils: Copying /home/***/.ivy2/jars/io.delta_delta-storage-3.1.0.jar to /tmp/spark-bb0a74ef-ee4c-4e95-9400-d611794b9721/userFiles-ef176ae0-9763-4e99-8a21-e727e8640e7a/io.delta_delta-storage-3.1.0.jar
[2025-06-04T10:58:10.217+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:10 INFO SparkContext: Added file file:///home/***/.ivy2/jars/org.antlr_antlr4-runtime-4.9.3.jar at spark://274c77453f4c:33287/files/org.antlr_antlr4-runtime-4.9.3.jar with timestamp 1749034689585
[2025-06-04T10:58:10.217+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:10 INFO Utils: Copying /home/***/.ivy2/jars/org.antlr_antlr4-runtime-4.9.3.jar to /tmp/spark-bb0a74ef-ee4c-4e95-9400-d611794b9721/userFiles-ef176ae0-9763-4e99-8a21-e727e8640e7a/org.antlr_antlr4-runtime-4.9.3.jar
[2025-06-04T10:58:10.264+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:10 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark-master:7077...
[2025-06-04T10:58:10.292+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:10 INFO TransportClientFactory: Successfully created connection to spark-master/172.19.0.6:7077 after 14 ms (0 ms spent in bootstraps)
[2025-06-04T10:58:10.368+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:10 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20250604105810-0001
[2025-06-04T10:58:10.372+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:10 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 38955.
[2025-06-04T10:58:10.373+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:10 INFO NettyBlockTransferService: Server created on 274c77453f4c:38955
[2025-06-04T10:58:10.374+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:10 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-06-04T10:58:10.377+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:10 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 274c77453f4c, 38955, None)
[2025-06-04T10:58:10.379+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:10 INFO BlockManagerMasterEndpoint: Registering block manager 274c77453f4c:38955 with 434.4 MiB RAM, BlockManagerId(driver, 274c77453f4c, 38955, None)
[2025-06-04T10:58:10.380+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:10 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 274c77453f4c, 38955, None)
[2025-06-04T10:58:10.381+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:10 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 274c77453f4c, 38955, None)
[2025-06-04T10:58:10.580+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:10 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2025-06-04T10:58:10.725+0000] {spark_submit.py:644} INFO - Bronze Ingestion: Spark session created.
[2025-06-04T10:58:10.729+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:10 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-06-04T10:58:10.791+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:10 WARN MetricsConfig: Cannot locate configuration: tried hadoop-metrics2-s3a-file-system.properties,hadoop-metrics2.properties
[2025-06-04T10:58:10.797+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:10 INFO MetricsSystemImpl: Scheduled Metric snapshot period at 10 second(s).
[2025-06-04T10:58:10.797+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:10 INFO MetricsSystemImpl: s3a-file-system metrics system started
[2025-06-04T10:58:11.084+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:11 INFO SharedState: Warehouse path is 's3a://mybucket'.
[2025-06-04T10:58:11.599+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:11 INFO InMemoryFileIndex: It took 23 ms to list leaf files for 1 paths.
[2025-06-04T10:58:11.997+0000] {spark_submit.py:644} INFO - Successfully loaded Stephen Curry stats from: /opt/***/data/Stephen Curry Stats.parquet
[2025-06-04T10:58:12.445+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:12 INFO HiveConf: Found configuration file null
[2025-06-04T10:58:12.450+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:12 INFO HiveUtils: Initializing HiveMetastoreConnection version 2.3.9 using Spark classes.
[2025-06-04T10:58:12.558+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:12 INFO HiveClientImpl: Warehouse location for Hive client (version 2.3.9) is s3a://mybucket
[2025-06-04T10:58:12.585+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:12 INFO metastore: Trying to connect to metastore with URI thrift://hive-metastore:9083
[2025-06-04T10:58:12.599+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:12 INFO metastore: Opened a connection to metastore, current connections: 1
[2025-06-04T10:58:12.618+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:12 INFO metastore: Connected to metastore.
[2025-06-04T10:58:12.964+0000] {spark_submit.py:644} INFO - Writing data to Bronze layer at: s3a://mybucket/bronze/curry_raw_data/
[2025-06-04T10:58:13.051+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:13 WARN SparkStringUtils: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.sql.debug.maxToStringFields'.
[2025-06-04T10:58:13.655+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:13 INFO DelegatingLogStore: LogStore `LogStoreAdapter(io.delta.storage.S3SingleDriverLogStore)` is used for scheme `s3a`
[2025-06-04T10:58:13.768+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:13 INFO DeltaLog: Loading version 4.
[2025-06-04T10:58:14.023+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:14 INFO DeltaLogFileIndex: Created DeltaLogFileIndex(JSON, numFilesInSegment: 5, totalFileSize: 11227)
[2025-06-04T10:58:14.152+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:14 INFO DataSourceStrategy: Pruning directories with:
[2025-06-04T10:58:14.155+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:14 INFO FileSourceStrategy: Pushed Filters:
[2025-06-04T10:58:14.156+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:14 INFO FileSourceStrategy: Post-Scan Filters: (isnotnull(protocol#150.minReaderVersion) OR isnotnull(metaData#149.id))
[2025-06-04T10:58:14.386+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:14 INFO CodeGenerator: Code generated in 142.8415 ms
[2025-06-04T10:58:14.411+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:14 INFO MemoryStore: Block broadcast_0 stored as values in memory (estimated size 205.2 KiB, free 434.2 MiB)
[2025-06-04T10:58:14.447+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:14 INFO MemoryStore: Block broadcast_0_piece0 stored as bytes in memory (estimated size 36.1 KiB, free 434.2 MiB)
[2025-06-04T10:58:14.449+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:14 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on 274c77453f4c:38955 (size: 36.1 KiB, free: 434.4 MiB)
[2025-06-04T10:58:14.452+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:14 INFO SparkContext: Created broadcast 0 from toString at String.java:4220
[2025-06-04T10:58:14.467+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:14 INFO FileSourceScanExec: Planning scan with bin packing, max size: 10491373 bytes, open cost is considered as scanning 4194304 bytes.
[2025-06-04T10:58:14.563+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:14 INFO SparkContext: Starting job: toString at String.java:4220
[2025-06-04T10:58:14.569+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:14 INFO DAGScheduler: Got job 0 (toString at String.java:4220) with 2 output partitions
[2025-06-04T10:58:14.570+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:14 INFO DAGScheduler: Final stage: ResultStage 0 (toString at String.java:4220)
[2025-06-04T10:58:14.570+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:14 INFO DAGScheduler: Parents of final stage: List()
[2025-06-04T10:58:14.570+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:14 INFO DAGScheduler: Missing parents: List()
[2025-06-04T10:58:14.572+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:14 INFO DAGScheduler: Submitting ResultStage 0 (MapPartitionsRDD[3] at toString at String.java:4220), which has no missing parents
[2025-06-04T10:58:14.580+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:14 INFO MemoryStore: Block broadcast_1 stored as values in memory (estimated size 40.1 KiB, free 434.1 MiB)
[2025-06-04T10:58:14.581+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:14 INFO MemoryStore: Block broadcast_1_piece0 stored as bytes in memory (estimated size 13.7 KiB, free 434.1 MiB)
[2025-06-04T10:58:14.582+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:14 INFO BlockManagerInfo: Added broadcast_1_piece0 in memory on 274c77453f4c:38955 (size: 13.7 KiB, free: 434.4 MiB)
[2025-06-04T10:58:14.582+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:14 INFO SparkContext: Created broadcast 1 from broadcast at DAGScheduler.scala:1585
[2025-06-04T10:58:14.592+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:14 INFO DAGScheduler: Submitting 2 missing tasks from ResultStage 0 (MapPartitionsRDD[3] at toString at String.java:4220) (first 15 tasks are for partitions Vector(0, 1))
[2025-06-04T10:58:14.593+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:14 INFO TaskSchedulerImpl: Adding task set 0.0 with 2 tasks resource profile 0
[2025-06-04T10:58:29.610+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:29 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T10:58:44.606+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:44 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T10:58:59.601+0000] {spark_submit.py:644} INFO - 25/06/04 10:58:59 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T10:59:14.602+0000] {spark_submit.py:644} INFO - 25/06/04 10:59:14 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T10:59:29.601+0000] {spark_submit.py:644} INFO - 25/06/04 10:59:29 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T10:59:44.603+0000] {spark_submit.py:644} INFO - 25/06/04 10:59:44 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T10:59:59.601+0000] {spark_submit.py:644} INFO - 25/06/04 10:59:59 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T11:00:14.602+0000] {spark_submit.py:644} INFO - 25/06/04 11:00:14 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T11:00:29.603+0000] {spark_submit.py:644} INFO - 25/06/04 11:00:29 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T11:00:44.608+0000] {spark_submit.py:644} INFO - 25/06/04 11:00:44 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T11:00:59.604+0000] {spark_submit.py:644} INFO - 25/06/04 11:00:59 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T11:01:14.604+0000] {spark_submit.py:644} INFO - 25/06/04 11:01:14 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T11:01:29.601+0000] {spark_submit.py:644} INFO - 25/06/04 11:01:29 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T11:01:44.605+0000] {spark_submit.py:644} INFO - 25/06/04 11:01:44 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T11:01:59.605+0000] {spark_submit.py:644} INFO - 25/06/04 11:01:59 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T11:02:14.602+0000] {spark_submit.py:644} INFO - 25/06/04 11:02:14 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T11:02:29.603+0000] {spark_submit.py:644} INFO - 25/06/04 11:02:29 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T11:02:44.602+0000] {spark_submit.py:644} INFO - 25/06/04 11:02:44 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T11:02:59.605+0000] {spark_submit.py:644} INFO - 25/06/04 11:02:59 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T11:03:14.600+0000] {spark_submit.py:644} INFO - 25/06/04 11:03:14 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T11:03:29.607+0000] {spark_submit.py:644} INFO - 25/06/04 11:03:29 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T11:03:44.603+0000] {spark_submit.py:644} INFO - 25/06/04 11:03:44 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T11:03:59.602+0000] {spark_submit.py:644} INFO - 25/06/04 11:03:59 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T11:04:14.604+0000] {spark_submit.py:644} INFO - 25/06/04 11:04:14 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T11:04:29.604+0000] {spark_submit.py:644} INFO - 25/06/04 11:04:29 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T11:04:44.606+0000] {spark_submit.py:644} INFO - 25/06/04 11:04:44 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T11:04:59.606+0000] {spark_submit.py:644} INFO - 25/06/04 11:04:59 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T11:05:14.603+0000] {spark_submit.py:644} INFO - 25/06/04 11:05:14 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T11:05:29.604+0000] {spark_submit.py:644} INFO - 25/06/04 11:05:29 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T11:05:44.606+0000] {spark_submit.py:644} INFO - 25/06/04 11:05:44 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T11:05:59.605+0000] {spark_submit.py:644} INFO - 25/06/04 11:05:59 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T11:06:14.605+0000] {spark_submit.py:644} INFO - 25/06/04 11:06:14 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T11:06:29.601+0000] {spark_submit.py:644} INFO - 25/06/04 11:06:29 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T11:06:44.601+0000] {spark_submit.py:644} INFO - 25/06/04 11:06:44 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T11:06:59.601+0000] {spark_submit.py:644} INFO - 25/06/04 11:06:59 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T11:07:14.603+0000] {spark_submit.py:644} INFO - 25/06/04 11:07:14 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T11:07:29.602+0000] {spark_submit.py:644} INFO - 25/06/04 11:07:29 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T11:07:44.604+0000] {spark_submit.py:644} INFO - 25/06/04 11:07:44 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T11:07:48.743+0000] {spark_submit.py:644} INFO - 25/06/04 11:07:48 INFO StandaloneAppClient$ClientEndpoint: Master removed worker worker-20250604105150-172.19.0.7-34225: 172.19.0.7:34225 got disassociated
[2025-06-04T11:07:48.744+0000] {spark_submit.py:644} INFO - 25/06/04 11:07:48 INFO StandaloneSchedulerBackend: Worker worker-20250604105150-172.19.0.7-34225 removed: 172.19.0.7:34225 got disassociated
[2025-06-04T11:07:48.750+0000] {spark_submit.py:644} INFO - 25/06/04 11:07:48 INFO TaskSchedulerImpl: Handle removed worker worker-20250604105150-172.19.0.7-34225: 172.19.0.7:34225 got disassociated
[2025-06-04T11:07:48.759+0000] {spark_submit.py:644} INFO - 25/06/04 11:07:48 INFO DAGScheduler: Shuffle files lost for worker worker-20250604105150-172.19.0.7-34225 on host 172.19.0.7
[2025-06-04T11:07:58.919+0000] {spark_submit.py:644} INFO - 25/06/04 11:07:58 WARN StandaloneAppClient$ClientEndpoint: Connection to spark-master:7077 failed; waiting for master to reconnect...
[2025-06-04T11:07:58.920+0000] {spark_submit.py:644} INFO - 25/06/04 11:07:58 WARN StandaloneSchedulerBackend: Disconnected from Spark cluster! Waiting for reconnection...
[2025-06-04T11:07:58.921+0000] {spark_submit.py:644} INFO - 25/06/04 11:07:58 WARN StandaloneAppClient$ClientEndpoint: Connection to spark-master:7077 failed; waiting for master to reconnect...
[2025-06-04T11:07:59.603+0000] {spark_submit.py:644} INFO - 25/06/04 11:07:59 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T11:08:14.604+0000] {spark_submit.py:644} INFO - 25/06/04 11:08:14 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T11:08:29.600+0000] {spark_submit.py:644} INFO - 25/06/04 11:08:29 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T11:08:44.604+0000] {spark_submit.py:644} INFO - 25/06/04 11:08:44 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T11:08:59.603+0000] {spark_submit.py:644} INFO - 25/06/04 11:08:59 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T11:09:14.603+0000] {spark_submit.py:644} INFO - 25/06/04 11:09:14 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T11:09:29.607+0000] {spark_submit.py:644} INFO - 25/06/04 11:09:29 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T11:09:44.605+0000] {spark_submit.py:644} INFO - 25/06/04 11:09:44 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T11:09:59.607+0000] {spark_submit.py:644} INFO - 25/06/04 11:09:59 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T11:10:14.600+0000] {spark_submit.py:644} INFO - 25/06/04 11:10:14 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T11:10:29.604+0000] {spark_submit.py:644} INFO - 25/06/04 11:10:29 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T11:10:44.604+0000] {spark_submit.py:644} INFO - 25/06/04 11:10:44 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T11:10:59.607+0000] {spark_submit.py:644} INFO - 25/06/04 11:10:59 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T11:11:14.602+0000] {spark_submit.py:644} INFO - 25/06/04 11:11:14 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T11:11:29.602+0000] {spark_submit.py:644} INFO - 25/06/04 11:11:29 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T11:11:44.603+0000] {spark_submit.py:644} INFO - 25/06/04 11:11:44 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T11:11:59.603+0000] {spark_submit.py:644} INFO - 25/06/04 11:11:59 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T11:12:14.605+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:14 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T11:12:29.604+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:29 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T11:12:44.602+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:44 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T11:12:59.602+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:59 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T11:13:14.606+0000] {spark_submit.py:644} INFO - 25/06/04 11:13:14 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T11:13:29.605+0000] {spark_submit.py:644} INFO - 25/06/04 11:13:29 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T11:13:44.611+0000] {spark_submit.py:644} INFO - 25/06/04 11:13:44 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T11:13:59.601+0000] {spark_submit.py:644} INFO - 25/06/04 11:13:59 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T11:14:14.605+0000] {spark_submit.py:644} INFO - 25/06/04 11:14:14 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T11:14:29.602+0000] {spark_submit.py:644} INFO - 25/06/04 11:14:29 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T11:14:37.428+0000] {local_task_job_runner.py:127} ERROR - Received SIGTERM. Terminating subprocesses
[2025-06-04T11:14:37.462+0000] {process_utils.py:132} INFO - Sending 15 to group 239. PIDs of all processes in the group: [241, 309, 239]
[2025-06-04T11:14:37.465+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 239
[2025-06-04T11:14:37.468+0000] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-06-04T11:14:37.471+0000] {spark_submit.py:770} INFO - Sending kill signal to spark-submit
[2025-06-04T11:14:37.576+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=309, status='terminated', started='10:58:08') (309) terminated with exit code None
[2025-06-04T11:14:38.377+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-06-04T11:14:38.382+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 3 for task submit_bronze_etl_job ((psycopg2.OperationalError) could not translate host name "postgres-***" to address: Name or service not known

(Background on this error at: https://sqlalche.me/e/14/e3q8); 239)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 197, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 555, in submit
    self._process_spark_submit_log(iter(self._submit_sp.stdout))  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 603, in _process_spark_submit_log
    for line in itr:
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3095, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres-***" to address: Name or service not known


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 318, in _run_raw_task
    ti.refresh_from_db(lock_for_update=True, session=session)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 2359, in refresh_from_db
    _refresh_from_db(task_instance=self, session=session, lock_for_update=lock_for_update)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 872, in _refresh_from_db
    ti = TaskInstance.get_task_instance(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/api_internal/internal_api_call.py", line 166, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 2341, in get_task_instance
    for attempt in run_with_db_retries(logger=cls.logger()):
  File "/home/airflow/.local/lib/python3.11/site-packages/tenacity/__init__.py", line 443, in __iter__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/tenacity/__init__.py", line 418, in exc_check
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/tenacity/__init__.py", line 185, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 2343, in get_task_instance
    return query.with_for_update().one_or_none()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2850, in one_or_none
    return self._iter().one_or_none()
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2916, in _iter
    result = self.session.execute(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres-***" to address: Name or service not known

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-06-04T11:14:38.452+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=241, status='terminated', started='10:57:39') (241) terminated with exit code None
[2025-06-04T11:14:38.457+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=239, status='terminated', exitcode=1, started='10:57:39') (239) terminated with exit code 1
[2025-06-04T11:14:38.459+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 143
[2025-06-04T11:14:38.468+0000] {taskinstance.py:3901} WARNING - Skipping mini scheduling run due to exception: None
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres-***" to address: Name or service not known


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3856, in _schedule_downstream_tasks
    ).one_or_none()
      ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2850, in one_or_none
    return self._iter().one_or_none()
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2916, in _iter
    result = self.session.execute(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres-***" to address: Name or service not known

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-06-04T11:14:39.475+0000] {job.py:239} ERROR - Job heartbeat failed with error
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres-***" to address: Name or service not known


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/jobs/job.py", line 207, in heartbeat
    self._merge_from(Job._fetch_from_db(self, session))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/api_internal/internal_api_call.py", line 166, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/retries.py", line 93, in wrapped_function
    for attempt in run_with_db_retries(max_retries=retries, logger=logger, **retry_kwargs):
  File "/home/airflow/.local/lib/python3.11/site-packages/tenacity/__init__.py", line 443, in __iter__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/tenacity/__init__.py", line 418, in exc_check
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/tenacity/__init__.py", line 185, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/retries.py", line 102, in wrapped_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/jobs/job.py", line 335, in _fetch_from_db
    session.merge(job)
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 3056, in merge
    return self._merge(
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 3136, in _merge
    merged = self.get(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2853, in get
    return self._get_impl(
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2975, in _get_impl
    return db_load_fn(
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres-***" to address: Name or service not known

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-06-04T11:14:39.478+0000] {job.py:245} ERROR - Job heartbeat failed with error. Scheduler may go into unhealthy state
[2025-06-04T11:14:39.478+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
