[2025-06-04T11:12:39.925+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-04T11:12:39.934+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: curry_medallion_etl.submit_bronze_etl_job manual__2025-06-04T11:12:38.214196+00:00 [queued]>
[2025-06-04T11:12:39.938+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: curry_medallion_etl.submit_bronze_etl_job manual__2025-06-04T11:12:38.214196+00:00 [queued]>
[2025-06-04T11:12:39.938+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-06-04T11:12:39.943+0000] {taskinstance.py:2889} INFO - Executing <Task(SparkSubmitOperator): submit_bronze_etl_job> on 2025-06-04 11:12:38.214196+00:00
[2025-06-04T11:12:39.946+0000] {standard_task_runner.py:72} INFO - Started process 546 to run task
[2025-06-04T11:12:39.948+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'curry_medallion_etl', 'submit_bronze_etl_job', 'manual__2025-06-04T11:12:38.214196+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/medallion_sales_etl_dag.py', '--cfg-path', '/tmp/tmpmwl9k7fb']
[2025-06-04T11:12:39.950+0000] {standard_task_runner.py:105} INFO - Job 5: Subtask submit_bronze_etl_job
[2025-06-04T11:12:39.977+0000] {task_command.py:467} INFO - Running <TaskInstance: curry_medallion_etl.submit_bronze_etl_job manual__2025-06-04T11:12:38.214196+00:00 [running]> on host 274c77453f4c
[2025-06-04T11:12:40.025+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='qdinh18' AIRFLOW_CTX_DAG_ID='curry_medallion_etl' AIRFLOW_CTX_TASK_ID='submit_bronze_etl_job' AIRFLOW_CTX_EXECUTION_DATE='2025-06-04T11:12:38.214196+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-04T11:12:38.214196+00:00'
[2025-06-04T11:12:40.025+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-06-04T11:12:40.068+0000] {base.py:84} INFO - Retrieving connection 'spark_default'
[2025-06-04T11:12:40.070+0000] {spark_submit.py:474} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --conf spark.executor.memory=2g --conf spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension --conf spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog --conf spark.hadoop.fs.s3a.endpoint=http://minio:9000 --conf spark.hadoop.fs.s3a.access.key=minioadmin --conf spark.hadoop.fs.s3a.secret.key=****** --conf spark.hadoop.fs.s3a.path.style.access=true --conf spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem --packages org.apache.hadoop:hadoop-aws:3.3.4,com.amazonaws:aws-java-sdk-bundle:1.12.262,io.delta:delta-spark_2.12:3.1.0 --name bronze_sc_stats_etl --verbose --queue root.default --deploy-mode client /opt/***/dags/bronze_ingestion_sc_stats_etl.py --output_path s3a://mybucket/bronze/curry_raw_data/
[2025-06-04T11:12:41.008+0000] {spark_submit.py:644} INFO - Using properties file: null
[2025-06-04T11:12:41.068+0000] {spark_submit.py:644} INFO - Parsed arguments:
[2025-06-04T11:12:41.072+0000] {spark_submit.py:644} INFO - master                  spark://spark-master:7077
[2025-06-04T11:12:41.072+0000] {spark_submit.py:644} INFO - remote                  null
[2025-06-04T11:12:41.072+0000] {spark_submit.py:644} INFO - deployMode              client
[2025-06-04T11:12:41.073+0000] {spark_submit.py:644} INFO - executorMemory          2g
[2025-06-04T11:12:41.073+0000] {spark_submit.py:644} INFO - executorCores           null
[2025-06-04T11:12:41.073+0000] {spark_submit.py:644} INFO - totalExecutorCores      null
[2025-06-04T11:12:41.073+0000] {spark_submit.py:644} INFO - propertiesFile          null
[2025-06-04T11:12:41.073+0000] {spark_submit.py:644} INFO - driverMemory            null
[2025-06-04T11:12:41.074+0000] {spark_submit.py:644} INFO - driverCores             null
[2025-06-04T11:12:41.074+0000] {spark_submit.py:644} INFO - driverExtraClassPath    null
[2025-06-04T11:12:41.074+0000] {spark_submit.py:644} INFO - driverExtraLibraryPath  null
[2025-06-04T11:12:41.074+0000] {spark_submit.py:644} INFO - driverExtraJavaOptions  null
[2025-06-04T11:12:41.074+0000] {spark_submit.py:644} INFO - supervise               false
[2025-06-04T11:12:41.074+0000] {spark_submit.py:644} INFO - queue                   root.default
[2025-06-04T11:12:41.074+0000] {spark_submit.py:644} INFO - numExecutors            null
[2025-06-04T11:12:41.075+0000] {spark_submit.py:644} INFO - files                   null
[2025-06-04T11:12:41.075+0000] {spark_submit.py:644} INFO - pyFiles                 null
[2025-06-04T11:12:41.075+0000] {spark_submit.py:644} INFO - archives                null
[2025-06-04T11:12:41.075+0000] {spark_submit.py:644} INFO - mainClass               null
[2025-06-04T11:12:41.075+0000] {spark_submit.py:644} INFO - primaryResource         file:/opt/***/dags/bronze_ingestion_sc_stats_etl.py
[2025-06-04T11:12:41.075+0000] {spark_submit.py:644} INFO - name                    bronze_sc_stats_etl
[2025-06-04T11:12:41.076+0000] {spark_submit.py:644} INFO - childArgs               [--output_path s3a://mybucket/bronze/curry_raw_data/]
[2025-06-04T11:12:41.076+0000] {spark_submit.py:644} INFO - jars                    null
[2025-06-04T11:12:41.076+0000] {spark_submit.py:644} INFO - packages                org.apache.hadoop:hadoop-aws:3.3.4,com.amazonaws:aws-java-sdk-bundle:1.12.262,io.delta:delta-spark_2.12:3.1.0
[2025-06-04T11:12:41.076+0000] {spark_submit.py:644} INFO - packagesExclusions      null
[2025-06-04T11:12:41.076+0000] {spark_submit.py:644} INFO - repositories            null
[2025-06-04T11:12:41.076+0000] {spark_submit.py:644} INFO - verbose                 true
[2025-06-04T11:12:41.077+0000] {spark_submit.py:644} INFO - 
[2025-06-04T11:12:41.077+0000] {spark_submit.py:644} INFO - Spark properties used, including those specified through
[2025-06-04T11:12:41.077+0000] {spark_submit.py:644} INFO - --conf and those from the properties file null:
[2025-06-04T11:12:41.077+0000] {spark_submit.py:644} INFO - (spark.executor.memory,2g)
[2025-06-04T11:12:41.077+0000] {spark_submit.py:644} INFO - (spark.hadoop.fs.s3a.access.key,*********(redacted))
[2025-06-04T11:12:41.077+0000] {spark_submit.py:644} INFO - (spark.hadoop.fs.s3a.endpoint,http://minio:9000)
[2025-06-04T11:12:41.077+0000] {spark_submit.py:644} INFO - (spark.hadoop.fs.s3a.impl,org.apache.hadoop.fs.s3a.S3AFileSystem)
[2025-06-04T11:12:41.078+0000] {spark_submit.py:644} INFO - (spark.hadoop.fs.s3a.path.style.access,true)
[2025-06-04T11:12:41.078+0000] {spark_submit.py:644} INFO - (spark.hadoop.fs.s3a.secret.key,*********(redacted))
[2025-06-04T11:12:41.078+0000] {spark_submit.py:644} INFO - (spark.sql.catalog.spark_catalog,org.apache.spark.sql.delta.catalog.DeltaCatalog)
[2025-06-04T11:12:41.078+0000] {spark_submit.py:644} INFO - (spark.sql.extensions,io.delta.sql.DeltaSparkSessionExtension)
[2025-06-04T11:12:41.078+0000] {spark_submit.py:644} INFO - 
[2025-06-04T11:12:41.078+0000] {spark_submit.py:644} INFO - 
[2025-06-04T11:12:41.148+0000] {spark_submit.py:644} INFO - :: loading settings :: url = jar:file:/home/***/.local/lib/python3.11/site-packages/pyspark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2025-06-04T11:12:41.195+0000] {spark_submit.py:644} INFO - Ivy Default Cache set to: /home/***/.ivy2/cache
[2025-06-04T11:12:41.195+0000] {spark_submit.py:644} INFO - The jars for the packages stored in: /home/***/.ivy2/jars
[2025-06-04T11:12:41.197+0000] {spark_submit.py:644} INFO - org.apache.hadoop#hadoop-aws added as a dependency
[2025-06-04T11:12:41.197+0000] {spark_submit.py:644} INFO - com.amazonaws#aws-java-sdk-bundle added as a dependency
[2025-06-04T11:12:41.198+0000] {spark_submit.py:644} INFO - io.delta#delta-spark_2.12 added as a dependency
[2025-06-04T11:12:41.198+0000] {spark_submit.py:644} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-21ba2b04-072c-4e98-bcd9-b7a2ee4b7324;1.0
[2025-06-04T11:12:41.198+0000] {spark_submit.py:644} INFO - confs: [default]
[2025-06-04T11:12:41.295+0000] {spark_submit.py:644} INFO - found org.apache.hadoop#hadoop-aws;3.3.4 in central
[2025-06-04T11:12:41.307+0000] {spark_submit.py:644} INFO - found com.amazonaws#aws-java-sdk-bundle;1.12.262 in central
[2025-06-04T11:12:41.318+0000] {spark_submit.py:644} INFO - found org.wildfly.openssl#wildfly-openssl;1.0.7.Final in central
[2025-06-04T11:12:41.326+0000] {spark_submit.py:644} INFO - found io.delta#delta-spark_2.12;3.1.0 in central
[2025-06-04T11:12:41.337+0000] {spark_submit.py:644} INFO - found io.delta#delta-storage;3.1.0 in central
[2025-06-04T11:12:41.345+0000] {spark_submit.py:644} INFO - found org.antlr#antlr4-runtime;4.9.3 in central
[2025-06-04T11:12:41.360+0000] {spark_submit.py:644} INFO - :: resolution report :: resolve 157ms :: artifacts dl 6ms
[2025-06-04T11:12:41.360+0000] {spark_submit.py:644} INFO - :: modules in use:
[2025-06-04T11:12:41.360+0000] {spark_submit.py:644} INFO - com.amazonaws#aws-java-sdk-bundle;1.12.262 from central in [default]
[2025-06-04T11:12:41.360+0000] {spark_submit.py:644} INFO - io.delta#delta-spark_2.12;3.1.0 from central in [default]
[2025-06-04T11:12:41.361+0000] {spark_submit.py:644} INFO - io.delta#delta-storage;3.1.0 from central in [default]
[2025-06-04T11:12:41.361+0000] {spark_submit.py:644} INFO - org.antlr#antlr4-runtime;4.9.3 from central in [default]
[2025-06-04T11:12:41.361+0000] {spark_submit.py:644} INFO - org.apache.hadoop#hadoop-aws;3.3.4 from central in [default]
[2025-06-04T11:12:41.361+0000] {spark_submit.py:644} INFO - org.wildfly.openssl#wildfly-openssl;1.0.7.Final from central in [default]
[2025-06-04T11:12:41.361+0000] {spark_submit.py:644} INFO - ---------------------------------------------------------------------
[2025-06-04T11:12:41.361+0000] {spark_submit.py:644} INFO - |                  |            modules            ||   artifacts   |
[2025-06-04T11:12:41.362+0000] {spark_submit.py:644} INFO - |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2025-06-04T11:12:41.362+0000] {spark_submit.py:644} INFO - ---------------------------------------------------------------------
[2025-06-04T11:12:41.362+0000] {spark_submit.py:644} INFO - |      default     |   6   |   0   |   0   |   0   ||   6   |   0   |
[2025-06-04T11:12:41.362+0000] {spark_submit.py:644} INFO - ---------------------------------------------------------------------
[2025-06-04T11:12:41.363+0000] {spark_submit.py:644} INFO - :: retrieving :: org.apache.spark#spark-submit-parent-21ba2b04-072c-4e98-bcd9-b7a2ee4b7324
[2025-06-04T11:12:41.363+0000] {spark_submit.py:644} INFO - confs: [default]
[2025-06-04T11:12:41.366+0000] {spark_submit.py:644} INFO - 0 artifacts copied, 6 already retrieved (0kB/3ms)
[2025-06-04T11:12:41.479+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:41 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-06-04T11:12:41.611+0000] {spark_submit.py:644} INFO - Main class:
[2025-06-04T11:12:41.611+0000] {spark_submit.py:644} INFO - org.apache.spark.deploy.PythonRunner
[2025-06-04T11:12:41.612+0000] {spark_submit.py:644} INFO - Arguments:
[2025-06-04T11:12:41.612+0000] {spark_submit.py:644} INFO - file:/opt/***/dags/bronze_ingestion_sc_stats_etl.py
[2025-06-04T11:12:41.612+0000] {spark_submit.py:644} INFO - file:///home/***/.ivy2/jars/org.apache.hadoop_hadoop-aws-3.3.4.jar,file:///home/***/.ivy2/jars/com.amazonaws_aws-java-sdk-bundle-1.12.262.jar,file:///home/***/.ivy2/jars/io.delta_delta-spark_2.12-3.1.0.jar,file:///home/***/.ivy2/jars/org.wildfly.openssl_wildfly-openssl-1.0.7.Final.jar,file:///home/***/.ivy2/jars/io.delta_delta-storage-3.1.0.jar,file:///home/***/.ivy2/jars/org.antlr_antlr4-runtime-4.9.3.jar
[2025-06-04T11:12:41.613+0000] {spark_submit.py:644} INFO - --output_path
[2025-06-04T11:12:41.613+0000] {spark_submit.py:644} INFO - s3a://mybucket/bronze/curry_raw_data/
[2025-06-04T11:12:41.613+0000] {spark_submit.py:644} INFO - Spark config:
[2025-06-04T11:12:41.614+0000] {spark_submit.py:644} INFO - (spark.app.name,bronze_sc_stats_etl)
[2025-06-04T11:12:41.614+0000] {spark_submit.py:644} INFO - (spark.app.submitTime,1749035561601)
[2025-06-04T11:12:41.614+0000] {spark_submit.py:644} INFO - (spark.executor.memory,2g)
[2025-06-04T11:12:41.615+0000] {spark_submit.py:644} INFO - (spark.files,file:///home/***/.ivy2/jars/org.apache.hadoop_hadoop-aws-3.3.4.jar,file:///home/***/.ivy2/jars/com.amazonaws_aws-java-sdk-bundle-1.12.262.jar,file:///home/***/.ivy2/jars/io.delta_delta-spark_2.12-3.1.0.jar,file:///home/***/.ivy2/jars/org.wildfly.openssl_wildfly-openssl-1.0.7.Final.jar,file:///home/***/.ivy2/jars/io.delta_delta-storage-3.1.0.jar,file:///home/***/.ivy2/jars/org.antlr_antlr4-runtime-4.9.3.jar)
[2025-06-04T11:12:41.615+0000] {spark_submit.py:644} INFO - (spark.hadoop.fs.s3a.access.key,*********(redacted))
[2025-06-04T11:12:41.615+0000] {spark_submit.py:644} INFO - (spark.hadoop.fs.s3a.endpoint,http://minio:9000)
[2025-06-04T11:12:41.615+0000] {spark_submit.py:644} INFO - (spark.hadoop.fs.s3a.impl,org.apache.hadoop.fs.s3a.S3AFileSystem)
[2025-06-04T11:12:41.615+0000] {spark_submit.py:644} INFO - (spark.hadoop.fs.s3a.path.style.access,true)
[2025-06-04T11:12:41.615+0000] {spark_submit.py:644} INFO - (spark.hadoop.fs.s3a.secret.key,*********(redacted))
[2025-06-04T11:12:41.616+0000] {spark_submit.py:644} INFO - (spark.jars,file:///home/***/.ivy2/jars/org.apache.hadoop_hadoop-aws-3.3.4.jar,file:///home/***/.ivy2/jars/com.amazonaws_aws-java-sdk-bundle-1.12.262.jar,file:///home/***/.ivy2/jars/io.delta_delta-spark_2.12-3.1.0.jar,file:///home/***/.ivy2/jars/org.wildfly.openssl_wildfly-openssl-1.0.7.Final.jar,file:///home/***/.ivy2/jars/io.delta_delta-storage-3.1.0.jar,file:///home/***/.ivy2/jars/org.antlr_antlr4-runtime-4.9.3.jar)
[2025-06-04T11:12:41.616+0000] {spark_submit.py:644} INFO - (spark.master,spark://spark-master:7077)
[2025-06-04T11:12:41.616+0000] {spark_submit.py:644} INFO - (spark.repl.local.jars,file:///home/***/.ivy2/jars/org.apache.hadoop_hadoop-aws-3.3.4.jar,file:///home/***/.ivy2/jars/com.amazonaws_aws-java-sdk-bundle-1.12.262.jar,file:///home/***/.ivy2/jars/io.delta_delta-spark_2.12-3.1.0.jar,file:///home/***/.ivy2/jars/org.wildfly.openssl_wildfly-openssl-1.0.7.Final.jar,file:///home/***/.ivy2/jars/io.delta_delta-storage-3.1.0.jar,file:///home/***/.ivy2/jars/org.antlr_antlr4-runtime-4.9.3.jar)
[2025-06-04T11:12:41.616+0000] {spark_submit.py:644} INFO - (spark.sql.catalog.spark_catalog,org.apache.spark.sql.delta.catalog.DeltaCatalog)
[2025-06-04T11:12:41.616+0000] {spark_submit.py:644} INFO - (spark.sql.extensions,io.delta.sql.DeltaSparkSessionExtension)
[2025-06-04T11:12:41.617+0000] {spark_submit.py:644} INFO - (spark.submit.deployMode,client)
[2025-06-04T11:12:41.617+0000] {spark_submit.py:644} INFO - (spark.submit.pyFiles,/home/***/.ivy2/jars/org.apache.hadoop_hadoop-aws-3.3.4.jar,/home/***/.ivy2/jars/com.amazonaws_aws-java-sdk-bundle-1.12.262.jar,/home/***/.ivy2/jars/io.delta_delta-spark_2.12-3.1.0.jar,/home/***/.ivy2/jars/org.wildfly.openssl_wildfly-openssl-1.0.7.Final.jar,/home/***/.ivy2/jars/io.delta_delta-storage-3.1.0.jar,/home/***/.ivy2/jars/org.antlr_antlr4-runtime-4.9.3.jar)
[2025-06-04T11:12:41.617+0000] {spark_submit.py:644} INFO - Classpath elements:
[2025-06-04T11:12:41.617+0000] {spark_submit.py:644} INFO - file:///home/***/.ivy2/jars/org.apache.hadoop_hadoop-aws-3.3.4.jar
[2025-06-04T11:12:41.617+0000] {spark_submit.py:644} INFO - file:///home/***/.ivy2/jars/com.amazonaws_aws-java-sdk-bundle-1.12.262.jar
[2025-06-04T11:12:41.618+0000] {spark_submit.py:644} INFO - file:///home/***/.ivy2/jars/io.delta_delta-spark_2.12-3.1.0.jar
[2025-06-04T11:12:41.618+0000] {spark_submit.py:644} INFO - file:///home/***/.ivy2/jars/org.wildfly.openssl_wildfly-openssl-1.0.7.Final.jar
[2025-06-04T11:12:41.618+0000] {spark_submit.py:644} INFO - file:///home/***/.ivy2/jars/io.delta_delta-storage-3.1.0.jar
[2025-06-04T11:12:41.618+0000] {spark_submit.py:644} INFO - file:///home/***/.ivy2/jars/org.antlr_antlr4-runtime-4.9.3.jar
[2025-06-04T11:12:41.619+0000] {spark_submit.py:644} INFO - 
[2025-06-04T11:12:41.619+0000] {spark_submit.py:644} INFO - 
[2025-06-04T11:12:42.407+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:42 INFO SparkContext: Running Spark version 3.5.2
[2025-06-04T11:12:42.407+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:42 INFO SparkContext: OS info Linux, 6.10.14-linuxkit, aarch64
[2025-06-04T11:12:42.407+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:42 INFO SparkContext: Java version 17.0.15
[2025-06-04T11:12:42.420+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:42 INFO ResourceUtils: ==============================================================
[2025-06-04T11:12:42.421+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:42 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-06-04T11:12:42.423+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:42 INFO ResourceUtils: ==============================================================
[2025-06-04T11:12:42.423+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:42 INFO SparkContext: Submitted application: BronzeIngestionStephenCurryStats
[2025-06-04T11:12:42.434+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:42 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(memory -> name: memory, amount: 2048, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-06-04T11:12:42.441+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:42 INFO ResourceProfile: Limiting resource is cpu
[2025-06-04T11:12:42.443+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:42 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-06-04T11:12:42.508+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:42 INFO SecurityManager: Changing view acls to: ***
[2025-06-04T11:12:42.509+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:42 INFO SecurityManager: Changing modify acls to: ***
[2025-06-04T11:12:42.509+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:42 INFO SecurityManager: Changing view acls groups to:
[2025-06-04T11:12:42.510+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:42 INFO SecurityManager: Changing modify acls groups to:
[2025-06-04T11:12:42.510+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:42 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: ***; groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY
[2025-06-04T11:12:42.669+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:42 INFO Utils: Successfully started service 'sparkDriver' on port 38461.
[2025-06-04T11:12:42.690+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:42 INFO SparkEnv: Registering MapOutputTracker
[2025-06-04T11:12:42.715+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:42 INFO SparkEnv: Registering BlockManagerMaster
[2025-06-04T11:12:42.725+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:42 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-06-04T11:12:42.726+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:42 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-06-04T11:12:42.728+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:42 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-06-04T11:12:42.743+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:42 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-30a82ffe-79b9-4d5f-9c64-822bb64b9e97
[2025-06-04T11:12:42.752+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:42 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-06-04T11:12:42.760+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:42 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-06-04T11:12:42.833+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:42 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-06-04T11:12:42.867+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:42 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2025-06-04T11:12:42.871+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:42 INFO Utils: Successfully started service 'SparkUI' on port 4041.
[2025-06-04T11:12:42.891+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:42 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/org.apache.hadoop_hadoop-aws-3.3.4.jar at spark://274c77453f4c:38461/jars/org.apache.hadoop_hadoop-aws-3.3.4.jar with timestamp 1749035562402
[2025-06-04T11:12:42.892+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:42 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/com.amazonaws_aws-java-sdk-bundle-1.12.262.jar at spark://274c77453f4c:38461/jars/com.amazonaws_aws-java-sdk-bundle-1.12.262.jar with timestamp 1749035562402
[2025-06-04T11:12:42.892+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:42 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/io.delta_delta-spark_2.12-3.1.0.jar at spark://274c77453f4c:38461/jars/io.delta_delta-spark_2.12-3.1.0.jar with timestamp 1749035562402
[2025-06-04T11:12:42.892+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:42 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/org.wildfly.openssl_wildfly-openssl-1.0.7.Final.jar at spark://274c77453f4c:38461/jars/org.wildfly.openssl_wildfly-openssl-1.0.7.Final.jar with timestamp 1749035562402
[2025-06-04T11:12:42.892+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:42 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/io.delta_delta-storage-3.1.0.jar at spark://274c77453f4c:38461/jars/io.delta_delta-storage-3.1.0.jar with timestamp 1749035562402
[2025-06-04T11:12:42.892+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:42 INFO SparkContext: Added JAR file:///home/***/.ivy2/jars/org.antlr_antlr4-runtime-4.9.3.jar at spark://274c77453f4c:38461/jars/org.antlr_antlr4-runtime-4.9.3.jar with timestamp 1749035562402
[2025-06-04T11:12:42.894+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:42 INFO SparkContext: Added file file:///home/***/.ivy2/jars/org.apache.hadoop_hadoop-aws-3.3.4.jar at spark://274c77453f4c:38461/files/org.apache.hadoop_hadoop-aws-3.3.4.jar with timestamp 1749035562402
[2025-06-04T11:12:42.894+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:42 INFO Utils: Copying /home/***/.ivy2/jars/org.apache.hadoop_hadoop-aws-3.3.4.jar to /tmp/spark-5c37199b-dd9d-4e5f-a1c2-f5ce2c52aee5/userFiles-cca73c2d-edc5-40a8-9dc4-9b87b922883f/org.apache.hadoop_hadoop-aws-3.3.4.jar
[2025-06-04T11:12:42.903+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:42 INFO SparkContext: Added file file:///home/***/.ivy2/jars/com.amazonaws_aws-java-sdk-bundle-1.12.262.jar at spark://274c77453f4c:38461/files/com.amazonaws_aws-java-sdk-bundle-1.12.262.jar with timestamp 1749035562402
[2025-06-04T11:12:42.903+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:42 INFO Utils: Copying /home/***/.ivy2/jars/com.amazonaws_aws-java-sdk-bundle-1.12.262.jar to /tmp/spark-5c37199b-dd9d-4e5f-a1c2-f5ce2c52aee5/userFiles-cca73c2d-edc5-40a8-9dc4-9b87b922883f/com.amazonaws_aws-java-sdk-bundle-1.12.262.jar
[2025-06-04T11:12:43.288+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:43 INFO SparkContext: Added file file:///home/***/.ivy2/jars/io.delta_delta-spark_2.12-3.1.0.jar at spark://274c77453f4c:38461/files/io.delta_delta-spark_2.12-3.1.0.jar with timestamp 1749035562402
[2025-06-04T11:12:43.289+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:43 INFO Utils: Copying /home/***/.ivy2/jars/io.delta_delta-spark_2.12-3.1.0.jar to /tmp/spark-5c37199b-dd9d-4e5f-a1c2-f5ce2c52aee5/userFiles-cca73c2d-edc5-40a8-9dc4-9b87b922883f/io.delta_delta-spark_2.12-3.1.0.jar
[2025-06-04T11:12:43.297+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:43 INFO SparkContext: Added file file:///home/***/.ivy2/jars/org.wildfly.openssl_wildfly-openssl-1.0.7.Final.jar at spark://274c77453f4c:38461/files/org.wildfly.openssl_wildfly-openssl-1.0.7.Final.jar with timestamp 1749035562402
[2025-06-04T11:12:43.298+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:43 INFO Utils: Copying /home/***/.ivy2/jars/org.wildfly.openssl_wildfly-openssl-1.0.7.Final.jar to /tmp/spark-5c37199b-dd9d-4e5f-a1c2-f5ce2c52aee5/userFiles-cca73c2d-edc5-40a8-9dc4-9b87b922883f/org.wildfly.openssl_wildfly-openssl-1.0.7.Final.jar
[2025-06-04T11:12:43.300+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:43 INFO SparkContext: Added file file:///home/***/.ivy2/jars/io.delta_delta-storage-3.1.0.jar at spark://274c77453f4c:38461/files/io.delta_delta-storage-3.1.0.jar with timestamp 1749035562402
[2025-06-04T11:12:43.301+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:43 INFO Utils: Copying /home/***/.ivy2/jars/io.delta_delta-storage-3.1.0.jar to /tmp/spark-5c37199b-dd9d-4e5f-a1c2-f5ce2c52aee5/userFiles-cca73c2d-edc5-40a8-9dc4-9b87b922883f/io.delta_delta-storage-3.1.0.jar
[2025-06-04T11:12:43.303+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:43 INFO SparkContext: Added file file:///home/***/.ivy2/jars/org.antlr_antlr4-runtime-4.9.3.jar at spark://274c77453f4c:38461/files/org.antlr_antlr4-runtime-4.9.3.jar with timestamp 1749035562402
[2025-06-04T11:12:43.303+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:43 INFO Utils: Copying /home/***/.ivy2/jars/org.antlr_antlr4-runtime-4.9.3.jar to /tmp/spark-5c37199b-dd9d-4e5f-a1c2-f5ce2c52aee5/userFiles-cca73c2d-edc5-40a8-9dc4-9b87b922883f/org.antlr_antlr4-runtime-4.9.3.jar
[2025-06-04T11:12:43.351+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:43 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark-master:7077...
[2025-06-04T11:12:43.379+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:43 INFO TransportClientFactory: Successfully created connection to spark-master/172.19.0.6:7077 after 16 ms (0 ms spent in bootstraps)
[2025-06-04T11:12:43.439+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:43 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20250604111243-0001
[2025-06-04T11:12:43.443+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:43 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 46797.
[2025-06-04T11:12:43.444+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:43 INFO NettyBlockTransferService: Server created on 274c77453f4c:46797
[2025-06-04T11:12:43.445+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:43 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-06-04T11:12:43.449+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:43 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 274c77453f4c, 46797, None)
[2025-06-04T11:12:43.450+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:43 INFO BlockManagerMasterEndpoint: Registering block manager 274c77453f4c:46797 with 434.4 MiB RAM, BlockManagerId(driver, 274c77453f4c, 46797, None)
[2025-06-04T11:12:43.452+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:43 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 274c77453f4c, 46797, None)
[2025-06-04T11:12:43.452+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:43 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 274c77453f4c, 46797, None)
[2025-06-04T11:12:43.560+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:43 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2025-06-04T11:12:43.698+0000] {spark_submit.py:644} INFO - Bronze Ingestion: Spark session created.
[2025-06-04T11:12:43.701+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:43 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-06-04T11:12:43.775+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:43 WARN MetricsConfig: Cannot locate configuration: tried hadoop-metrics2-s3a-file-system.properties,hadoop-metrics2.properties
[2025-06-04T11:12:43.782+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:43 INFO MetricsSystemImpl: Scheduled Metric snapshot period at 10 second(s).
[2025-06-04T11:12:43.783+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:43 INFO MetricsSystemImpl: s3a-file-system metrics system started
[2025-06-04T11:12:44.166+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:44 INFO SharedState: Warehouse path is 's3a://mybucket'.
[2025-06-04T11:12:44.736+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:44 INFO InMemoryFileIndex: It took 19 ms to list leaf files for 1 paths.
[2025-06-04T11:12:45.124+0000] {spark_submit.py:644} INFO - Successfully loaded Stephen Curry stats from: /opt/***/data/Stephen Curry Stats.parquet
[2025-06-04T11:12:45.579+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:45 INFO HiveConf: Found configuration file null
[2025-06-04T11:12:45.585+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:45 INFO HiveUtils: Initializing HiveMetastoreConnection version 2.3.9 using Spark classes.
[2025-06-04T11:12:45.704+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:45 INFO HiveClientImpl: Warehouse location for Hive client (version 2.3.9) is s3a://mybucket
[2025-06-04T11:12:45.728+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:45 INFO metastore: Trying to connect to metastore with URI thrift://hive-metastore:9083
[2025-06-04T11:12:45.743+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:45 INFO metastore: Opened a connection to metastore, current connections: 1
[2025-06-04T11:12:45.763+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:45 INFO metastore: Connected to metastore.
[2025-06-04T11:12:45.985+0000] {spark_submit.py:644} INFO - Writing data to Bronze layer at: s3a://mybucket/bronze/curry_raw_data/
[2025-06-04T11:12:46.064+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:46 WARN SparkStringUtils: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.sql.debug.maxToStringFields'.
[2025-06-04T11:12:46.731+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:46 INFO DelegatingLogStore: LogStore `LogStoreAdapter(io.delta.storage.S3SingleDriverLogStore)` is used for scheme `s3a`
[2025-06-04T11:12:46.875+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:46 INFO DeltaLog: Loading version 4.
[2025-06-04T11:12:47.126+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:47 INFO DeltaLogFileIndex: Created DeltaLogFileIndex(JSON, numFilesInSegment: 5, totalFileSize: 11227)
[2025-06-04T11:12:47.256+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:47 INFO DataSourceStrategy: Pruning directories with:
[2025-06-04T11:12:47.260+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:47 INFO FileSourceStrategy: Pushed Filters:
[2025-06-04T11:12:47.263+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:47 INFO FileSourceStrategy: Post-Scan Filters: (isnotnull(protocol#150.minReaderVersion) OR isnotnull(metaData#149.id))
[2025-06-04T11:12:47.510+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:47 INFO CodeGenerator: Code generated in 150.291167 ms
[2025-06-04T11:12:47.537+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:47 INFO MemoryStore: Block broadcast_0 stored as values in memory (estimated size 205.2 KiB, free 434.2 MiB)
[2025-06-04T11:12:47.578+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:47 INFO MemoryStore: Block broadcast_0_piece0 stored as bytes in memory (estimated size 36.1 KiB, free 434.2 MiB)
[2025-06-04T11:12:47.583+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:47 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on 274c77453f4c:46797 (size: 36.1 KiB, free: 434.4 MiB)
[2025-06-04T11:12:47.588+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:47 INFO SparkContext: Created broadcast 0 from toString at String.java:4220
[2025-06-04T11:12:47.602+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:47 INFO FileSourceScanExec: Planning scan with bin packing, max size: 10491373 bytes, open cost is considered as scanning 4194304 bytes.
[2025-06-04T11:12:47.704+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:47 INFO SparkContext: Starting job: toString at String.java:4220
[2025-06-04T11:12:47.713+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:47 INFO DAGScheduler: Got job 0 (toString at String.java:4220) with 2 output partitions
[2025-06-04T11:12:47.714+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:47 INFO DAGScheduler: Final stage: ResultStage 0 (toString at String.java:4220)
[2025-06-04T11:12:47.716+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:47 INFO DAGScheduler: Parents of final stage: List()
[2025-06-04T11:12:47.716+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:47 INFO DAGScheduler: Missing parents: List()
[2025-06-04T11:12:47.717+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:47 INFO DAGScheduler: Submitting ResultStage 0 (MapPartitionsRDD[3] at toString at String.java:4220), which has no missing parents
[2025-06-04T11:12:47.728+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:47 INFO MemoryStore: Block broadcast_1 stored as values in memory (estimated size 40.1 KiB, free 434.1 MiB)
[2025-06-04T11:12:47.729+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:47 INFO MemoryStore: Block broadcast_1_piece0 stored as bytes in memory (estimated size 13.8 KiB, free 434.1 MiB)
[2025-06-04T11:12:47.730+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:47 INFO BlockManagerInfo: Added broadcast_1_piece0 in memory on 274c77453f4c:46797 (size: 13.8 KiB, free: 434.4 MiB)
[2025-06-04T11:12:47.730+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:47 INFO SparkContext: Created broadcast 1 from broadcast at DAGScheduler.scala:1585
[2025-06-04T11:12:47.767+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:47 INFO DAGScheduler: Submitting 2 missing tasks from ResultStage 0 (MapPartitionsRDD[3] at toString at String.java:4220) (first 15 tasks are for partitions Vector(0, 1))
[2025-06-04T11:12:47.768+0000] {spark_submit.py:644} INFO - 25/06/04 11:12:47 INFO TaskSchedulerImpl: Adding task set 0.0 with 2 tasks resource profile 0
[2025-06-04T11:13:02.784+0000] {spark_submit.py:644} INFO - 25/06/04 11:13:02 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T11:13:17.782+0000] {spark_submit.py:644} INFO - 25/06/04 11:13:17 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T11:13:32.780+0000] {spark_submit.py:644} INFO - 25/06/04 11:13:32 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T11:13:47.783+0000] {spark_submit.py:644} INFO - 25/06/04 11:13:47 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T11:14:02.781+0000] {spark_submit.py:644} INFO - 25/06/04 11:14:02 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T11:14:17.780+0000] {spark_submit.py:644} INFO - 25/06/04 11:14:17 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T11:14:26.666+0000] {spark_submit.py:644} INFO - 25/06/04 11:14:26 INFO StandaloneAppClient$ClientEndpoint: Master removed worker worker-20250604111126-172.19.0.7-45615: 172.19.0.7:45615 got disassociated
[2025-06-04T11:14:26.669+0000] {spark_submit.py:644} INFO - 25/06/04 11:14:26 INFO StandaloneSchedulerBackend: Worker worker-20250604111126-172.19.0.7-45615 removed: 172.19.0.7:45615 got disassociated
[2025-06-04T11:14:26.670+0000] {spark_submit.py:644} INFO - 25/06/04 11:14:26 INFO TaskSchedulerImpl: Handle removed worker worker-20250604111126-172.19.0.7-45615: 172.19.0.7:45615 got disassociated
[2025-06-04T11:14:26.673+0000] {spark_submit.py:644} INFO - 25/06/04 11:14:26 INFO DAGScheduler: Shuffle files lost for worker worker-20250604111126-172.19.0.7-45615 on host 172.19.0.7
[2025-06-04T11:14:32.783+0000] {spark_submit.py:644} INFO - 25/06/04 11:14:32 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-06-04T11:14:36.862+0000] {spark_submit.py:644} INFO - 25/06/04 11:14:36 WARN StandaloneAppClient$ClientEndpoint: Connection to spark-master:7077 failed; waiting for master to reconnect...
[2025-06-04T11:14:36.867+0000] {spark_submit.py:644} INFO - 25/06/04 11:14:36 WARN StandaloneSchedulerBackend: Disconnected from Spark cluster! Waiting for reconnection...
[2025-06-04T11:14:36.868+0000] {spark_submit.py:644} INFO - 25/06/04 11:14:36 WARN StandaloneAppClient$ClientEndpoint: Connection to spark-master:7077 failed; waiting for master to reconnect...
[2025-06-04T11:14:37.423+0000] {local_task_job_runner.py:127} ERROR - Received SIGTERM. Terminating subprocesses
[2025-06-04T11:14:37.445+0000] {process_utils.py:132} INFO - Sending 15 to group 546. PIDs of all processes in the group: [548, 608, 546]
[2025-06-04T11:14:37.448+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 546
[2025-06-04T11:14:37.464+0000] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-06-04T11:14:37.466+0000] {spark_submit.py:770} INFO - Sending kill signal to spark-submit
[2025-06-04T11:14:37.804+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=608, status='terminated', started='11:12:41') (608) terminated with exit code None
[2025-06-04T11:14:38.609+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-06-04T11:14:38.610+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 5 for task submit_bronze_etl_job ((psycopg2.OperationalError) could not translate host name "postgres-***" to address: Name or service not known

(Background on this error at: https://sqlalche.me/e/14/e3q8); 546)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 197, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 555, in submit
    self._process_spark_submit_log(iter(self._submit_sp.stdout))  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 603, in _process_spark_submit_log
    for line in itr:
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3095, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres-***" to address: Name or service not known


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 318, in _run_raw_task
    ti.refresh_from_db(lock_for_update=True, session=session)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 2359, in refresh_from_db
    _refresh_from_db(task_instance=self, session=session, lock_for_update=lock_for_update)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 872, in _refresh_from_db
    ti = TaskInstance.get_task_instance(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/api_internal/internal_api_call.py", line 166, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 2341, in get_task_instance
    for attempt in run_with_db_retries(logger=cls.logger()):
  File "/home/airflow/.local/lib/python3.11/site-packages/tenacity/__init__.py", line 443, in __iter__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/tenacity/__init__.py", line 418, in exc_check
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/tenacity/__init__.py", line 185, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 2343, in get_task_instance
    return query.with_for_update().one_or_none()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2850, in one_or_none
    return self._iter().one_or_none()
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2916, in _iter
    result = self.session.execute(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres-***" to address: Name or service not known

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-06-04T11:14:38.659+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=546, status='terminated', exitcode=1, started='11:12:39') (546) terminated with exit code 1
[2025-06-04T11:14:38.659+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=548, status='terminated', started='11:12:40') (548) terminated with exit code None
[2025-06-04T11:14:38.660+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 143
[2025-06-04T11:14:38.665+0000] {taskinstance.py:3901} WARNING - Skipping mini scheduling run due to exception: None
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres-***" to address: Name or service not known


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3856, in _schedule_downstream_tasks
    ).one_or_none()
      ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2850, in one_or_none
    return self._iter().one_or_none()
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2916, in _iter
    result = self.session.execute(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres-***" to address: Name or service not known

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-06-04T11:14:39.055+0000] {job.py:239} ERROR - Job heartbeat failed with error
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres-***" to address: Name or service not known


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/jobs/job.py", line 207, in heartbeat
    self._merge_from(Job._fetch_from_db(self, session))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/api_internal/internal_api_call.py", line 166, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/retries.py", line 93, in wrapped_function
    for attempt in run_with_db_retries(max_retries=retries, logger=logger, **retry_kwargs):
  File "/home/airflow/.local/lib/python3.11/site-packages/tenacity/__init__.py", line 443, in __iter__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/tenacity/__init__.py", line 418, in exc_check
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/tenacity/__init__.py", line 185, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/retries.py", line 102, in wrapped_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/jobs/job.py", line 335, in _fetch_from_db
    session.merge(job)
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 3056, in merge
    return self._merge(
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 3136, in _merge
    merged = self.get(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2853, in get
    return self._get_impl(
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2975, in _get_impl
    return db_load_fn(
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres-***" to address: Name or service not known

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-06-04T11:14:39.058+0000] {job.py:245} ERROR - Job heartbeat failed with error. Scheduler may go into unhealthy state
[2025-06-04T11:14:39.058+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
