[2025-06-03T04:11:38.144+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-03T04:11:38.157+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: curry_medallion_etl.ensure_datalake_bucket_exists manual__2025-06-03T04:11:36.963428+00:00 [queued]>
[2025-06-03T04:11:38.161+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: curry_medallion_etl.ensure_datalake_bucket_exists manual__2025-06-03T04:11:36.963428+00:00 [queued]>
[2025-06-03T04:11:38.162+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-06-03T04:11:38.169+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): ensure_datalake_bucket_exists> on 2025-06-03 04:11:36.963428+00:00
[2025-06-03T04:11:38.172+0000] {standard_task_runner.py:72} INFO - Started process 5021 to run task
[2025-06-03T04:11:38.174+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'curry_medallion_etl', 'ensure_datalake_bucket_exists', 'manual__2025-06-03T04:11:36.963428+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/medallion_sales_etl_dag.py', '--cfg-path', '/tmp/tmp738qz1hj']
[2025-06-03T04:11:38.176+0000] {standard_task_runner.py:105} INFO - Job 37: Subtask ensure_datalake_bucket_exists
[2025-06-03T04:11:38.216+0000] {task_command.py:467} INFO - Running <TaskInstance: curry_medallion_etl.ensure_datalake_bucket_exists manual__2025-06-03T04:11:36.963428+00:00 [running]> on host 083f94398a74
[2025-06-03T04:11:38.281+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='qdinh18' AIRFLOW_CTX_DAG_ID='curry_medallion_etl' AIRFLOW_CTX_TASK_ID='ensure_datalake_bucket_exists' AIRFLOW_CTX_EXECUTION_DATE='2025-06-03T04:11:36.963428+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-03T04:11:36.963428+00:00'
[2025-06-03T04:11:38.282+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-06-03T04:11:38.298+0000] {logging_mixin.py:190} INFO - Bucket 'mybucket' already exists.
[2025-06-03T04:11:38.307+0000] {python.py:240} INFO - Done. Returned value was: True
[2025-06-03T04:11:38.319+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-06-03T04:11:38.320+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=curry_medallion_etl, task_id=ensure_datalake_bucket_exists, run_id=manual__2025-06-03T04:11:36.963428+00:00, execution_date=20250603T041136, start_date=20250603T041138, end_date=20250603T041138
[2025-06-03T04:11:38.357+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-06-03T04:11:38.373+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-06-03T04:11:38.374+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
