[2025-06-03T07:17:42.296+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-03T07:17:42.306+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: curry_medallion_etl.ensure_datalake_bucket_exists manual__2025-06-03T07:17:42.038314+00:00 [queued]>
[2025-06-03T07:17:42.312+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: curry_medallion_etl.ensure_datalake_bucket_exists manual__2025-06-03T07:17:42.038314+00:00 [queued]>
[2025-06-03T07:17:42.312+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-06-03T07:17:42.319+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): ensure_datalake_bucket_exists> on 2025-06-03 07:17:42.038314+00:00
[2025-06-03T07:17:42.322+0000] {standard_task_runner.py:72} INFO - Started process 1707 to run task
[2025-06-03T07:17:42.324+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'curry_medallion_etl', 'ensure_datalake_bucket_exists', 'manual__2025-06-03T07:17:42.038314+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/medallion_sales_etl_dag.py', '--cfg-path', '/tmp/tmpaojvkntz']
[2025-06-03T07:17:42.326+0000] {standard_task_runner.py:105} INFO - Job 9: Subtask ensure_datalake_bucket_exists
[2025-06-03T07:17:42.364+0000] {task_command.py:467} INFO - Running <TaskInstance: curry_medallion_etl.ensure_datalake_bucket_exists manual__2025-06-03T07:17:42.038314+00:00 [running]> on host eff93630df4f
[2025-06-03T07:17:42.446+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='qdinh18' AIRFLOW_CTX_DAG_ID='curry_medallion_etl' AIRFLOW_CTX_TASK_ID='ensure_datalake_bucket_exists' AIRFLOW_CTX_EXECUTION_DATE='2025-06-03T07:17:42.038314+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-03T07:17:42.038314+00:00'
[2025-06-03T07:17:42.447+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-06-03T07:17:42.460+0000] {logging_mixin.py:190} INFO - Bucket 'mybucket' already exists.
[2025-06-03T07:17:42.461+0000] {python.py:240} INFO - Done. Returned value was: True
[2025-06-03T07:17:42.476+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-06-03T07:17:42.476+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=curry_medallion_etl, task_id=ensure_datalake_bucket_exists, run_id=manual__2025-06-03T07:17:42.038314+00:00, execution_date=20250603T071742, start_date=20250603T071742, end_date=20250603T071742
[2025-06-03T07:17:42.506+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-06-03T07:17:42.522+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-06-03T07:17:42.522+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
