[2025-06-01T06:36:44.985+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-01T06:36:44.996+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: medallion_sales_etl.ensure_datalake_bucket_exists manual__2025-06-01T06:36:44.721261+00:00 [queued]>
[2025-06-01T06:36:45.000+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: medallion_sales_etl.ensure_datalake_bucket_exists manual__2025-06-01T06:36:44.721261+00:00 [queued]>
[2025-06-01T06:36:45.000+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-06-01T06:36:45.006+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): ensure_datalake_bucket_exists> on 2025-06-01 06:36:44.721261+00:00
[2025-06-01T06:36:45.008+0000] {standard_task_runner.py:72} INFO - Started process 197 to run task
[2025-06-01T06:36:45.011+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'medallion_sales_etl', 'ensure_datalake_bucket_exists', 'manual__2025-06-01T06:36:44.721261+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/medallion_sales_etl_dag.py', '--cfg-path', '/tmp/tmp9uyllmyp']
[2025-06-01T06:36:45.012+0000] {standard_task_runner.py:105} INFO - Job 2: Subtask ensure_datalake_bucket_exists
[2025-06-01T06:36:45.043+0000] {task_command.py:467} INFO - Running <TaskInstance: medallion_sales_etl.ensure_datalake_bucket_exists manual__2025-06-01T06:36:44.721261+00:00 [running]> on host 5272c5e55b21
[2025-06-01T06:36:45.089+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='qdinh18' AIRFLOW_CTX_DAG_ID='medallion_sales_etl' AIRFLOW_CTX_TASK_ID='ensure_datalake_bucket_exists' AIRFLOW_CTX_EXECUTION_DATE='2025-06-01T06:36:44.721261+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-01T06:36:44.721261+00:00'
[2025-06-01T06:36:45.090+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-06-01T06:36:45.110+0000] {logging_mixin.py:190} INFO - Bucket 'qdinh18' already exists.
[2025-06-01T06:36:45.119+0000] {python.py:240} INFO - Done. Returned value was: True
[2025-06-01T06:36:45.131+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-06-01T06:36:45.132+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=medallion_sales_etl, task_id=ensure_datalake_bucket_exists, run_id=manual__2025-06-01T06:36:44.721261+00:00, execution_date=20250601T063644, start_date=20250601T063644, end_date=20250601T063645
[2025-06-01T06:36:45.152+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-06-01T06:36:45.167+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-06-01T06:36:45.168+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
