[2025-06-07T10:11:07.714+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-07T10:11:07.724+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: curry_medallion_etl.ensure_datalake_bucket_exists manual__2025-06-07T10:11:06.750018+00:00 [queued]>
[2025-06-07T10:11:07.729+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: curry_medallion_etl.ensure_datalake_bucket_exists manual__2025-06-07T10:11:06.750018+00:00 [queued]>
[2025-06-07T10:11:07.730+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-06-07T10:11:07.736+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): ensure_datalake_bucket_exists> on 2025-06-07 10:11:06.750018+00:00
[2025-06-07T10:11:07.740+0000] {standard_task_runner.py:72} INFO - Started process 3799 to run task
[2025-06-07T10:11:07.742+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'curry_medallion_etl', 'ensure_datalake_bucket_exists', 'manual__2025-06-07T10:11:06.750018+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/medallion_sales_etl_dag.py', '--cfg-path', '/tmp/tmpkh7qibpe']
[2025-06-07T10:11:07.743+0000] {standard_task_runner.py:105} INFO - Job 23: Subtask ensure_datalake_bucket_exists
[2025-06-07T10:11:07.775+0000] {task_command.py:467} INFO - Running <TaskInstance: curry_medallion_etl.ensure_datalake_bucket_exists manual__2025-06-07T10:11:06.750018+00:00 [running]> on host 1ed3a5ab4297
[2025-06-07T10:11:07.827+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='qdinh18' AIRFLOW_CTX_DAG_ID='curry_medallion_etl' AIRFLOW_CTX_TASK_ID='ensure_datalake_bucket_exists' AIRFLOW_CTX_EXECUTION_DATE='2025-06-07T10:11:06.750018+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-07T10:11:06.750018+00:00'
[2025-06-07T10:11:07.827+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-06-07T10:11:07.838+0000] {logging_mixin.py:190} INFO - Bucket 'mybucket' already exists.
[2025-06-07T10:11:07.838+0000] {python.py:240} INFO - Done. Returned value was: True
[2025-06-07T10:11:07.853+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-06-07T10:11:07.854+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=curry_medallion_etl, task_id=ensure_datalake_bucket_exists, run_id=manual__2025-06-07T10:11:06.750018+00:00, execution_date=20250607T101106, start_date=20250607T101107, end_date=20250607T101107
[2025-06-07T10:11:07.883+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-06-07T10:11:07.899+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-06-07T10:11:07.900+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
