[2025-06-01T06:38:22.761+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-01T06:38:22.775+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: medallion_sales_etl.ensure_datalake_bucket_exists manual__2025-06-01T06:38:22.402770+00:00 [queued]>
[2025-06-01T06:38:22.780+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: medallion_sales_etl.ensure_datalake_bucket_exists manual__2025-06-01T06:38:22.402770+00:00 [queued]>
[2025-06-01T06:38:22.780+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-06-01T06:38:22.791+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): ensure_datalake_bucket_exists> on 2025-06-01 06:38:22.402770+00:00
[2025-06-01T06:38:22.794+0000] {standard_task_runner.py:72} INFO - Started process 386 to run task
[2025-06-01T06:38:22.796+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'medallion_sales_etl', 'ensure_datalake_bucket_exists', 'manual__2025-06-01T06:38:22.402770+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/medallion_sales_etl_dag.py', '--cfg-path', '/tmp/tmp7ml49h4m']
[2025-06-01T06:38:22.800+0000] {standard_task_runner.py:105} INFO - Job 4: Subtask ensure_datalake_bucket_exists
[2025-06-01T06:38:22.832+0000] {task_command.py:467} INFO - Running <TaskInstance: medallion_sales_etl.ensure_datalake_bucket_exists manual__2025-06-01T06:38:22.402770+00:00 [running]> on host 5272c5e55b21
[2025-06-01T06:38:22.879+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='qdinh18' AIRFLOW_CTX_DAG_ID='medallion_sales_etl' AIRFLOW_CTX_TASK_ID='ensure_datalake_bucket_exists' AIRFLOW_CTX_EXECUTION_DATE='2025-06-01T06:38:22.402770+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-01T06:38:22.402770+00:00'
[2025-06-01T06:38:22.879+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-06-01T06:38:22.889+0000] {logging_mixin.py:190} INFO - Bucket 'qdinh18' already exists.
[2025-06-01T06:38:22.898+0000] {python.py:240} INFO - Done. Returned value was: True
[2025-06-01T06:38:22.910+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-06-01T06:38:22.911+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=medallion_sales_etl, task_id=ensure_datalake_bucket_exists, run_id=manual__2025-06-01T06:38:22.402770+00:00, execution_date=20250601T063822, start_date=20250601T063822, end_date=20250601T063822
[2025-06-01T06:38:22.935+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-06-01T06:38:22.951+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-06-01T06:38:22.952+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
